# Generated by Django 4.2.6 on 2023-11-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well', models.IntegerField(verbose_name='Well Number')),
                ('service', models.CharField(max_length=100, verbose_name='Service')),
                ('date_done', models.DateField(verbose_name='Date Done')),
                ('field', models.CharField(blank=True, max_length=100, verbose_name='Field')),
                ('jacket', models.CharField(blank=True, max_length=100, verbose_name='Jacket')),
                ('supervisor', models.CharField(blank=True, max_length=100, verbose_name='Supervisor')),
                ('comments', models.TextField(blank=True, verbose_name='Comments')),
            ],
        ),
    ]
